apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: etl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: etl
  name: spark-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmap"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: etl
subjects:
- kind: ServiceAccount
  name: spark
  namespace: etl
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io

